### PR TITLE
Migrated to Java 8, Spring 5.0, Spring Boot 2.0

### PR DESCRIPTION
**Pull request by Pirat83**

### CODE REVIEW

**Comment by neumaennl** [comment]
looks fine to me

**Comment by Pirat83** [comment]
Hi @neumaennl, when do you release this feature?

**Comment by neumaennl** [comment]
@Pirat83 That is not for me to decide. @dilipkrish has the final word on this. Especially since your change makes this work only with the latest snapshot version of Springfox and is probably not backwards-compatible.

**Comment by dilipkrish** [comment]
@Pirat83 Thanks for the PR and @neumaennl thanks for reviewing, I figured you have commiter/merge access. Do you not have that?

**Review by dilipkrish — APPROVED** [review]

**Comment by neumaennl** [comment]
@dilipkrish did you read my message? I don't really know if it's okay to merge this because the change makes this work only with the latest snapshot version of Springfox and is probably not backwards-compatible.
If this is okay for you, then please merge it.

**Comment by dilipkrish** [comment]
@neumaennl sorry I've been busy with my day job. I'll look at this in a bit

**Comment by eranation** [comment]
@dilipkrish any chance to bump this? :)

**Pull request closed without merging**
